gateway:
  ip: 193.1.130.82

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0


ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000